language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.4.1

install: bundle install --jobs=3 --retry=3 --without production

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER testuser WITH PASSWORD 'testpass';" -U postgres

script:
  - 'HANAMI_ENV=test bundle exec hanami db migrate'
  - 'bundle exec rake test'
