version: "3"

services:
  app:
    build: .
    # command: bundle exec hanami server --host=0.0.0.0
    command: bash
    volumes:
      - ./:/usr/src/app
    ports:
      - "2300:2300"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:9.6.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: atm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
